apiVersion: apps/v1
kind: Deployment
metadata:
  name: resonite-querybug
  namespace: resonite-querybug
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resonite-querybug
  template:
    metadata:
      labels:
        app: resonite-querybug
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: resonite-querybug
        image: harbor.noodlebug.network/resonite-querybug/querybug:450b6fc
        ports:
        - containerPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: resonite-querybug-service-ingress
  namespace: resonite-querybug
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: querybug.noodle-bug.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: resonite-querybug-service
            port:
              number: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: resonite-querybug-service
  namespace: resonite-querybug
spec:
  type: ClusterIP
  selector:
    app: resonite-querybug
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
