apiVersion: v1
kind: Service
metadata:
  name: resonite-querybug-service
  namespace: resonite-querybug
spec:
  type: ClusterIP
  selector:
    app: resonite-querybug
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
