apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: resonite-querybug-service-ingress
  namespace: resonite-querybug
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: querybug.noodle-bug.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: resonite-querybug-service
            port:
              number: 8080
