name: Build and Push Docker Image

on:
  push:
    tags:
      - v*
      
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_ACTION_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: | 
          TAG="${GITHUB_REF#refs/tags/}"
          docker build -t harbor.noodlebug.network/resonite-querybug/querybug:$TAG .

      - name: Save Docker image as tarball
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          docker save harbor.noodlebug.network/resonite-querybug/querybug:$TAG > image.tar

      - name: Download regctl
        run: |
          curl -L https://github.com/regclient/regclient/releases/download/v0.8.2/regctl-linux-amd64 -o regctl
          chmod +x regctl

      - name: Log into Harbor
        env:
          HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
          HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}
        run: |
          docker login harbor.noodlebug.network --username $HARBOR_USERNAME --password $HARBOR_PASSWORD

      - name: Push Docker image with regctl
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          ./regctl registry set --blob-chunk 20971520 --blob-max 104857600 harbor.noodlebug.network
          ./regctl image import harbor.noodlebug.network/resonite-querybug/querybug:$TAG image.tar -v info

      - name: Checkout main branch
        run: |
          git fetch origin main
          git checkout main

      - name: Update kube.yaml with new image tag
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          IMAGE_NAME="harbor.noodlebug.network/resonite-querybug/querybug"
          sed -i "s#${IMAGE_NAME}:[a-zA-Z0-9_.-]*#${IMAGE_NAME}:${TAG}#g" kube.yaml

      - name: Update package.json version
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          VERSION="${TAG#v}"
          jq --arg ver "$VERSION" '.version = $ver' package.json > package.tmp && mv package.tmp package.json

      - name: Commit updated manifest and package.json
        run: |
          git config --global user.email "ci@example.com"
          git config --global user.name "GitHub Actions CI"
          git add kube.yaml package.json
          git commit -m "Update image tag to ${TAG} and package.json version to ${VERSION}" || echo "No changes to commit"
          git push
